name: "Build dcompass on various targets"
on:
  push:
  schedule:
    - cron: '30 1 * * */7'
jobs:
  build:
    if: (startsWith(github.event.head_commit.message, 'build:') || (github.event_name == 'schedule'))
    name: Automated builds
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H')"

    - name: Install musl
      run: sudo apt-get install musl-tools

    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-unknown-linux-musl

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: armv7-unknown-linux-musleabi

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: armv5te-unknown-linux-musleabi

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-gnu

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-apple-darwin

    - uses: actions-rs/install@v0.1
      with:
        crate: cross
        version: latest
        use-tool-cache: true

    - name: Build
      run: ./build.sh

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: This is an automated build running for supported architechtures periodically.
        tag_name: Build ${{ steps.date.outputs.date }}
        prerelease: true
        files: |
          LICENSE
          dcompass-x86_64-unknown-linux-musl.zip
          dcompass-armv7-unknown-linux-muslabi.zip
          dcompass-armv5te-unknown-linux-musleabi.zip
          dcompass-x86_64-pc-windows-gnu.zip
          dcompass-x86_64-apple-darwin.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
